#!/bin/bash

# Update system
sudo apt-get update
sudo apt-get upgrade -y

# Get user input for hostname
read -p "Enter hostname: " hostname

# Validate hostname
while [[ ! $hostname =~ ^[a-zA-Z0-9-]+$ ]]; do
    read -p "Invalid hostname. Enter hostname again: " hostname
done

# Set system hostname
sudo hostnamectl set-hostname "pb-$hostname"

# Set up VLAN
sudo tee /etc/network/interfaces.d/vlan <<EOF
auto eth0.41
iface eth0.41 inet static
    address 192.168.1.100
    netmask 255.255.255.0
    vlan-raw-device eth0
EOF

# Install Debian packages from pisetup/
sudo dpkg -i /pishare/dev/lh/pibox/pisetup/*.deb

# Copy config.txt to /boot/firmware
sudo cp -f ./config.txt /boot/firmware



